// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjxtAqCERV2levmXmHQoqnK8U6BMNtCng',
    appId: '1:771255612100:web:d02b17d6ca8b8debf20f91',
    messagingSenderId: '771255612100',
    projectId: 'yalladrive-b4b66',
    authDomain: 'yalladrive-b4b66.firebaseapp.com',
    storageBucket: 'yalladrive-b4b66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZsI_BLd_ibA2imJvAj8KB410FTg38QVU',
    appId: '1:771255612100:android:73e66672d29d3e5ef20f91',
    messagingSenderId: '771255612100',
    projectId: 'yalladrive-b4b66',
    storageBucket: 'yalladrive-b4b66.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDes_NEzg54vUy-qPH0x7n0OfRdouR1Wa4',
    appId: '1:771255612100:ios:98647adce167cb28f20f91',
    messagingSenderId: '771255612100',
    projectId: 'yalladrive-b4b66',
    storageBucket: 'yalladrive-b4b66.firebasestorage.app',
    iosBundleId: 'com.example.yalladrive',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDes_NEzg54vUy-qPH0x7n0OfRdouR1Wa4',
    appId: '1:771255612100:ios:98647adce167cb28f20f91',
    messagingSenderId: '771255612100',
    projectId: 'yalladrive-b4b66',
    storageBucket: 'yalladrive-b4b66.firebasestorage.app',
    iosBundleId: 'com.example.yalladrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjxtAqCERV2levmXmHQoqnK8U6BMNtCng',
    appId: '1:771255612100:web:7c2e40c9ec4cdc78f20f91',
    messagingSenderId: '771255612100',
    projectId: 'yalladrive-b4b66',
    authDomain: 'yalladrive-b4b66.firebaseapp.com',
    storageBucket: 'yalladrive-b4b66.firebasestorage.app',
  );
}
